name: walk
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  cloud_firestore: ^5.6.12
  kakao_flutter_sdk_user: ^1.9.7+3
  flutter_dotenv: ^5.2.1
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  google_sign_in: ^6.2.0
  geolocator: ^12.0.0
  http: ^1.2.1
  geocoding: ^3.0.0
  google_maps_flutter: ^2.6.1
  image_picker: ^1.1.2
  firebase_storage: ^12.4.10
  flutter_local_notifications: ^17.1.2
  cached_network_image: ^3.2.3
  firebase_app_check: ^0.3.2+10 # 최신 버전 확인 (pub.dev에서 확인)
  firebase_analytics: ^11.4.12
  share_plus: ^7.2.2
  path_provider: ^2.1.4
  intl: ^0.19.0
  provider: ^6.1.2
  fluttertoast: ^8.2.8
  lottie: ^2.7.0
  flutter_compass: ^0.8.0
  video_player: ^2.8.6
  flutter_email_sender: ^6.0.3
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/config/.env
    - assets/animations/

  fonts:
    - family: Cafe24Oneprettynight
      fonts:
        - asset: assets/fonts/Cafe24Oneprettynight-v2.0.otf

# 런처 아이콘 설정
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21
  
  # Android 세부 설정
  adaptive_icon_background: "#ffffff"  # 흰색 배경 (필요시 색상 변경)
  adaptive_icon_foreground: "assets/images/app_icon.png"
  
  # iOS 세부 설정  
  remove_alpha_ios: true
  
  # 웹, 윈도우, 맥 설정
  web:
    generate: true
    image_path: "assets/images/app_icon.png"
  windows:
    generate: true
    image_path: "assets/images/app_icon.png"
  macos:
    generate: true
    image_path: "assets/images/app_icon.png"



